nagisa/rust_libloading

README.mkd

The README includes a link to a subpage of the docs, so it could also use one to the docs main page :).

Include a link to the docs

---

src/util.rs

The code is already very clean, so here's just one fixed warning.

fixed one clippy warning

---

src/lib.rs

These are some changes to the docs to encourage users passively, by example, to mark the extern functions as `unsafe`, instead of exposing `unsafe` functions as `safe`.
Also changed that all examples are compiled. In the process this caught the error in an example where the function expects `f64`(aka `0.0` or `0f64`) but it receives an `integral type`(`0`), yey for Rust doc tests :smile:

Discourage users from exposing unsafe functions as safe

---

src/lib.rs
src/os/unix/mod.rs
src/os/windows/mod.rs

I have been using your library pretty extensively one of my projects. This project has an event system which allows functions from many dlls to be called at one callsite. Currently, for each event I have to store an Rc or Arc to each Symbol it may call. This means that I have to pay for the ref-count increment/decrement plus the overhead of interlocking for Arc and then I have to dereference each symbol to make the call. My events could simply store the Symbol itself, but the Symbol struct does not provide a clone trait. The derives I added here are sufficient for providing Clone for these structs.

Allow symbols to be cloned.

---

src/os/unix/mod.rs

Noticed a couple of typos while browsing the libloading sources.

Fix typos in unix/mod.rs

---

src/os/unix/mod.rs
src/os/windows/mod.rs
tests/send.rs

Make Library (Unix only) and Symbol (anywhere) implement Sync

---

build.rs

Solaris don't need to link against any particularly library for the dl*() functions to be available.

Allow to build on Solaris.

---

Cargo.toml
src/os/windows/mod.rs

This pull request updated `libloading` to `winapi` 0.3.
This greatly improves compilation time on Windows since it only enables the required features. On my machine, a clean build went from 20 seconds with the old version to 3 seconds with the new version.

Update to winapi 0.3

---

build.rs

This pull request allows libloading to recognise and compile successfully on Haiku. Tested on x86_64-unknown-haiku and passes all [tests](https://gist.github.com/return/160c298ca1e2a68a0378cd4a69b36a86).

Add support for building on Haiku.

---

src/lib.rs
src/os/unix/mod.rs
src/os/windows/mod.rs
tests/functions.rs

Otherwise it leads to a double-free, once in `close` and another time in
`drop`. Curiously this was only a bug on Windows, and Unix code was
fine. Not sure how this happened.
Fixes #82

Don't neglect to forget `self` in `close`

---

.github/workflows/libloading.yml
src/error.rs
src/os/windows/mod.rs
tests/functions.rs

Fixes the Windows half of https://github.com/nagisa/rust_libloading/issues/27.
For unix I guess I can make a cfg-gated function? Not sure which platforms though. Also, if so, should I also add a cfg-gated top-level `Library` function?

Library::open_already_loaded() for Windows

---

Cargo.toml
README.mkd
src/lib.rs
src/os/mod.rs
src/os/unix/consts.rs
src/os/unix/mod.rs
src/os/windows/mod.rs
src/util.rs
tests/functions.rs

I've found this library extremely useful in several projects and I'm very grateful for it. I have however found that, as a native English speaker, the documentation does not read particularly clearly in parts and there are some very minor grammatical errors. I have gone through all of the documentation and amended the grammar and phrasing in some places to improve the overall quality of the documentation and I hope this is useful to the project.
I found that there was quite a mix of American and British English spellings in the documentation (for example, "initialise" and "initialize" were used interchangeably). More of the spelling used British English so I chose to change the American spellings into the British ones to make the documentation more consistent. If you would like me to …

Made the documentation more idiomatic and fixed some small grammatical errors

---

.github/workflows/libloading.yml
Cargo.toml
src/changelog.rs
src/lib.rs
src/os/mod.rs
src/os/unix/consts.rs
src/os/unix/mod.rs
src/os/windows/mod.rs
src/safe.rs

`docsrs` is a commonly used `cfg` identifier and if there are issues in
the implementation of libloading with nightly features, it can cause
downstream crates to fail to document as well. Similarly if the upstream
crates use this cfg and they fail to document, libloading itself would
then fail to document as well.
Using a cfg specific to a crate is all-in-all just better.
Fixes #101

Replace `docsrs` cfg with `libloading_docs`

---

.github/workflows/libloading.yml
Cargo.toml
src/os/windows/mod.rs
tests/functions.rs

[windows-sys](https://github.com/microsoft/windows-rs) is a crate with bindings to the windows API that is maintained by Microsoft. A lot of crates are migrating from `winapi` to it, and it would be nice for `libloading` to migrate as well.
The changes are quite straightforward:
- the DWORD, WCHAR, etc types are not exposed by windows-sys, the standard types are used instead: u32, u16, etc.
- HMODULE does not exist, HINSTANCE is used instead, and is a `isize` instead of a pointer.
- FARPROC is a `Option<unsafe extern "system" fn() -> isize>`, which is a bit more annoying to use in debug prints: I used the `{:#x}` formatter instead of the `{:p}` one: before: ``, after: `Symbol@0x7ffb29135bf0`.
Closes #118

Replace winapi with windows-sys

---

Cargo.toml

It is the only crate that pulls the old version of windows crates
Untested as I don't have access to a windows machine. I saw https://github.com/nagisa/rust_libloading/pull/125 already, but as a short term solution, maybe merging this patch & doing a release would be a good step forward to reduce the amount of windows deps that ends up being pulled by using this crate

misc: Update windows-sys dep

---

.github/workflows/libloading.yml
Cargo.toml
src/changelog.rs
src/lib.rs
src/os/unix/mod.rs
src/os/windows/mod.rs

This results in a smaller dependency tree for the users and a slightly less maintenance burden for me (I won’t be losing any sleep over outdated dependency now!)
I have chose to make this a patch-point release. I believe this is an entirely compatible release – `LOAD_LIBRARY_FLAGS` is the same typedef to u32 before and after. `HMOODULE` is the same `isize`, etc. The negative is that documentation now displays method types with resolved type names (i.e. `isize` instead of `HMODULE`) which is not great. I would love to make tyese newtypes, but that's gonna need to wait for a breaking change.

windows: drop dependency on windows-sys

---

src/changelog.rs
src/error.rs
src/os/unix/mod.rs

Useful for those who are using platform-specific openers like `dlmopen`.

unix: expose with_dlerror to the end users

---

Cargo.toml

The windows-sys dependency is only relevant on cfg(windows) targets.

windows: make windows-sys dev-dependency target-specific

---

Cargo.toml
src/changelog.rs
src/os/unix/consts.rs

Fixes #149
@coolbluewater please check if this works for you.

apple: add cfgs for tvos/watchos/visionos

---

src/os/unix/mod.rs
src/os/windows/mod.rs
src/safe.rs
tests/functions.rs
tests/windows.rs

see https://github.com/nagisa/rust_libloading/issues/153

Add try_as_raw_ptr/as_raw_ptr implementations for Symbol to convert to raw pointer

---

src/error.rs

fix: make Error::source return GetModuleHandleExW source

---

Cargo.toml

Things appear to compile and test fine, so 🫡 woot!

build: allow `windows-core` 0.59, `windows-targets` 0.53

---

.github/workflows/libloading.yml
Cargo.toml
src/changelog.rs

Release 0.8.7
